version: "3.7"

networks:
  host:
    driver: bridge
  backend:
    internal: true
    name: "backend"
    ipam:
      config:
        - subnet: 10.0.0.0/8

volumes:
  postgres-drive:
    name: "postgres-drive"

services:
  
  zeo:
    build: zeodbsync
    restart: always
    ports:
      - 9999
    volumes:
      - type: bind
        source: ./mounts
        target: /vol
    networks:
      - backend
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - LANG=en_US.utf8
      - POSTGRES_USER=dockerzope
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dockerzope
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/vol/data
    ports:
      - 5432
    volumes:
      - postgres-drive:/vol
    networks:
      - backend
  
  zope:
    build: zope
    restart: always
    networks:
      - backend
    volumes:
      - type: bind
        source: ./mounts
        target: /vol
  
  haproxy:
    build: haproxy
    restart: always
    ports:
      - "0.0.0.0:80:80/tcp"
    networks:
      - backend
      - host

  ws_broadcast:
    build: ws_broadcast
    restart: always
    ports:
      - "0.0.0.0:4242:4242/tcp"
    networks:
      - backend
      - host
